version: '3.7'

services:
  bitbucket-repository-backup:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/var/www/html/:consistent
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - default